# Generated by Django 3.1.6 on 2021-02-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudex',
            name='last_login',
            field=models.DateTimeField(blank=True),
        ),
    ]
