# Generated by Django 3.1.6 on 2021-02-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0003_auto_20210223_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crudex',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='crudex',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
